const SUPABASE_URL="https://mlqaeginqsgqacdqdzbm.supabase.co";
const SUPABASE_KEY="sb_publishable_3YeUDTX-15GB95pP5d4M8g_ulPQczdi";
let db=null;
async function loadSupabase(){if(db)return db;if(!window.supabase)await new Promise((r,j)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=r;s.onerror=()=>j(new Error("Không tải được Supabase JS"));document.head.appendChild(s)});db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return db}
const state={page:"home",candidate:"",code:"",subject:"",exam:null,answers:{},startedAt:0,timer:null,lastResult:null};let exams=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function loadExams(){try{await loadSupabase();const {data,error}=await db.from("exams").select("*").eq("status","active").order("created_at",{ascending:false});if(error)throw error;exams=(data||[]).map(e=>({...e,questions:Array.isArray(e.questions)?e.questions:[]}));}catch(e){console.error(e);exams=[]}}
function header(){return `<header class="top"><div class="brand">🎓 STUDY TEST AI</div><div class="nav"><button onclick="go('home')">Trang chủ</button><button onclick="go('history')">📊 Lịch sử</button><button onclick="go('admin')">Admin</button></div></header>`}
function page(){
 if(state.page==="home")return `<main class="container"><div class="card"><h1>Tạo và làm bài kiểm tra</h1><p class="muted">Nhập tên thí sinh trước khi chọn bài.</p><label>Họ và tên</label><input id="candidate" placeholder="Ví dụ: Nguyễn Văn A" value="${esc(state.candidate)}"><label>Mã học sinh</label><input id="code" placeholder="HS001" value="${esc(state.code)}"></div><div class="card"><h2>Chọn môn</h2><div class="grid">${["Toán","Tiếng Anh","Ngữ Văn"].map((s,i)=>`<button class="subject" onclick="chooseSubject('${s}')"><b>${["📐","🇬🇧","📖"][i]} ${s}</b><span class="muted">${exams.filter(e=>e.subject===s).length} bài kiểm tra</span></button>`).join("")}</div></div></main>`;
 if(state.page==="subject"){const list=exams.filter(e=>e.subject===state.subject);return `<main class="container"><div class="card"><button class="btn secondary" onclick="go('home')">← Quay lại</button><h1>${esc(state.subject)}</h1>${list.length?list.map(examCard).join(""):"<p>Chưa có bài kiểm tra.</p>"}</div></main>`}
 if(state.page==="exam")return examPage();
 if(state.page==="result")return resultPage();
 if(state.page==="history")return `<main class="container"><div class="card"><h1>📊 Lịch sử</h1><p>Điểm của bạn được lưu trong phiên hiện tại.</p>${state.lastResult?`<p><b>${esc(state.lastResult.examTitle)}</b> — ${state.lastResult.score}% (${state.lastResult.correct}/${state.lastResult.total})</p>`:"Chưa có lượt làm."}<button class="btn" onclick="go('home')">Về trang chủ</button></div></main>`;
 if(state.page==="admin")return `<main class="container"><div class="card"><h1>👨‍💼 Admin</h1><a class="btn" href="/admin/">Mở Admin Dashboard</a></div></main>`;
 return "";
}
function examCard(e){const n=Array.isArray(e.questions)?e.questions.length:Number(e.question_count||0);return `<div class="exam"><div><span class="pill">${n} câu</span><span class="pill">⏱ ${Number(e.duration||0)} phút</span><h3>${esc(e.title)}</h3><div class="muted">${esc(e.difficulty||"")}</div></div><button class="btn" onclick="startExam('${e.id}')" ${n?"":"disabled"}>Bắt đầu</button></div>`}
function chooseSubject(s){state.candidate=document.getElementById("candidate")?.value.trim()||state.candidate;state.code=document.getElementById("code")?.value.trim()||state.code;if(!state.candidate)return alert("Hãy nhập họ tên trước.");state.subject=s;state.page="subject";render()}
function startExam(id){state.exam=exams.find(e=>String(e.id)===String(id));if(!state.exam)return alert("Không tìm thấy bài kiểm tra.");if(!state.exam.questions.length)return alert("Bài này chưa có câu hỏi.");state.answers={};state.startedAt=Date.now();state.page="exam";render();startTimer()}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(updateTimer,1000);updateTimer()}
function updateTimer(){if(state.page!=="exam")return clearInterval(state.timer);const left=Math.max(0,Number(state.exam.duration||0)*60-Math.floor((Date.now()-state.startedAt)/1000));const el=document.getElementById("timer");if(el)el.textContent=`⏱ ${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;if(left<=0)submitExam(true)}
function examPage(){const qs=state.exam.questions||[];return `<main class="container"><div class="timer" id="timer">⏱ --:--</div><div class="card"><h1>${esc(state.exam.title)}</h1><p class="muted">Thí sinh: <b>${esc(state.candidate)}</b> · ${qs.length} câu</p>${qs.map(renderQuestion).join("")}<button class="btn" onclick="submitExam(false)">NỘP BÀI</button></div></main>`}
function renderQuestion(q,i){const type=q.type||"mcq";
 if(type==="true_false")return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b>${(q.statements||[]).map((s,j)=>`<div class="option"><span>${String.fromCharCode(97+j)}. ${esc(s)}</span><label><input type="radio" name="q${i}_${j}" onchange="setTF(${i},${j},true)"> Đúng</label><label><input type="radio" name="q${i}_${j}" onchange="setTF(${i},${j},false)"> Sai</label></div>`).join("")}</div>`;
 if(type==="short")return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b><div class="short-answer" style="display:flex;gap:6px;margin-top:10px">${[0,1,2,3].map(j=>`<input maxlength="1" inputmode="text" style="width:48px;text-align:center" oninput="setShort(${i},${j},this.value)" value="${esc((state.answers[i]?.[j]||""))}">`).join("")}</div></div>`;
 return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b>${(q.opts||[]).slice(0,4).map((o,j)=>`<label class="option"><input type="radio" name="q${i}" onchange="state.answers[${i}]=${j}"> ${String.fromCharCode(65+j)}. ${esc(o)}</label>`).join("")}</div>`;
}
function setTF(i,j,v){if(!Array.isArray(state.answers[i]))state.answers[i]=[];state.answers[i][j]=v}
function setShort(i,j,v){if(!Array.isArray(state.answers[i]))state.answers[i]=["","","",""];state.answers[i][j]=v}
async function submitExam(auto=false){if(!state.exam)return;clearInterval(state.timer);const qs=state.exam.questions||[];let correct=0;qs.forEach((q,i)=>{if(q.type==="true_false"){const a=state.answers[i]||[];const r=q.answers||[];if(r.length&&r.every((v,j)=>a[j]===v))correct++}else if(q.type==="short"){const a=(state.answers[i]||[]).join("").trim().toLowerCase();const r=String(q.answer??"").trim().toLowerCase();if(a===r)correct++}else if(Number(state.answers[i])===Number(q.a))correct++});const total=qs.length,score=total?Math.round(correct/total*100):0;try{await loadSupabase();await db.from("participants").insert({name:state.candidate,code:state.code||null});await db.from("attempts").insert({student_name:state.candidate,exam_title:state.exam.title,score,created_at:new Date().toISOString()})}catch(e){console.warn(e)}state.lastResult={examTitle:state.exam.title,candidate:state.candidate,score,correct,total,auto};state.page="result";render()}
function resultPage(){const r=state.lastResult;return `<main class="container"><div class="card"><h1>🎉 Hoàn thành</h1><p style="text-align:center">${esc(r.candidate)} · ${esc(r.examTitle)}</p><div class="score">${r.score}%</div><p style="text-align:center">Đúng <b>${r.correct}/${r.total}</b> câu</p><p style="text-align:center">${r.auto?"⏰ Hết giờ, hệ thống tự nộp bài.":"Bài đã được nộp thành công."}</p><div style="text-align:center"><button class="btn" onclick="go('history')">Xem lịch sử</button><button class="btn secondary" onclick="go('home')">Về trang chủ</button></div></div></main>`}
function go(p){state.page=p;render();if(p==="home")loadExams()}
async function render(){document.getElementById("app").innerHTML=header()+page()}
(async()=>{await loadExams();await render()})();
