const SUPABASE_URL="https://mlqaeginqsgqacdqdzbm.supabase.co";
const SUPABASE_KEY="sb_publishable_3YeUDTX-15GB95pP5d4M8g_ulPQczdi";
let db=null;
async function loadSupabase(){if(db)return db;if(!window.supabase)await new Promise((r,j)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=r;s.onerror=()=>j(new Error("Không tải được Supabase JS"));document.head.appendChild(s)});db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);return db}
const DEVICE_KEY="study_device_id_v2";
const state={page:"home",candidate:"",code:"",subject:"",exam:null,answers:{},startedAt:0,timer:null,lastResult:null,history:[],review:null,thread:null,messages:[]};let exams=[];
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():"dev_"+Date.now()+"_"+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,id)}return id}
async function clientMeta(){try{const r=await fetch("/api/client-meta");return await r.json()}catch{return {ip:null,userAgent:navigator.userAgent}}}
async function registerDevice(){try{await loadSupabase();const meta=await clientMeta();await db.from("user_devices").upsert({device_id:deviceId(),last_seen:new Date().toISOString(),last_ip:meta.ip,user_agent:meta.userAgent},{onConflict:"device_id"})}catch(e){console.warn("registerDevice",e)}}
async function loadExams(){try{await loadSupabase();const {data,error}=await db.from("exams").select("*").eq("status","active").order("created_at",{ascending:false});if(error)throw error;exams=(data||[]).map(e=>({...e,questions:Array.isArray(e.questions)?e.questions:[]}))}catch(e){console.error(e);exams=[]}}
async function loadHistory(){try{await loadSupabase();const {data,error}=await db.from("user_attempts").select("*").eq("device_id",deviceId()).order("created_at",{ascending:false});if(error)throw error;state.history=data||[]}catch(e){console.warn("history",e);state.history=[]}}
function header(){return `<header class="top"><div class="brand">🎓 STUDY TEST AI</div><div class="nav"><button onclick="go('home')">Trang chủ</button><button onclick="go('history')">📊 Lịch sử</button><button onclick="go('support')">💬 Hỗ trợ</button><button onclick="go('admin')">Admin</button></div></header>`}
function page(){
 if(state.page==="home")return `<main class="container"><div class="card"><h1>Tạo và làm bài kiểm tra</h1><p class="muted">Nhập tên thí sinh trước khi chọn bài. Lịch sử được lưu theo thiết bị.</p><label>Họ và tên</label><input id="candidate" placeholder="Ví dụ: Nguyễn Văn A" value="${esc(state.candidate)}"><label>Mã học sinh <span class="muted">(không bắt buộc)</span></label><input id="code" placeholder="HS001" value="${esc(state.code)}"></div><div class="card"><h2>Chọn môn</h2><div class="grid">${["Toán","Tiếng Anh","Ngữ Văn"].map((s,i)=>`<button class="subject" onclick="chooseSubject('${s}')"><b>${["📐","🇬🇧","📖"][i]} ${s}</b><span class="muted">${exams.filter(e=>e.subject===s).length} bài kiểm tra</span></button>`).join("")}</div></div><div class="card"><h2>💬 Cần hỗ trợ?</h2><p class="muted">Bạn có thể nhắn trực tiếp cho Admin về lỗi gặp phải.</p><button class="btn" onclick="go('support')">Mở chat với Admin</button></div></main>`;
 if(state.page==="subject"){const list=exams.filter(e=>e.subject===state.subject);return `<main class="container"><div class="card"><button class="btn secondary" onclick="go('home')">← Quay lại</button><h1>${esc(state.subject)}</h1>${list.length?list.map(examCard).join(""):"<p>Chưa có bài kiểm tra.</p>"}</div></main>`}
 if(state.page==="exam")return examPage();
 if(state.page==="result")return resultPage();
 if(state.page==="history")return historyPage();
 if(state.page==="review")return reviewPage();
 if(state.page==="support")return supportPage();
 if(state.page==="admin")return `<main class="container"><div class="card"><h1>👨‍💼 Admin</h1><a class="btn" href="/admin/">Mở Admin Dashboard</a></div></main>`;
 return "";
}
function examCard(e){const n=Array.isArray(e.questions)?e.questions.length:Number(e.question_count||0);return `<div class="exam"><div><span class="pill">${n} câu</span><span class="pill">⏱ ${Number(e.duration||0)} phút</span><h3>${esc(e.title)}</h3><div class="muted">${esc(e.difficulty||"")}</div></div><button class="btn" onclick="startExam('${e.id}')" ${n?"":"disabled"}>Bắt đầu</button></div>`}
function chooseSubject(s){state.candidate=document.getElementById("candidate")?.value.trim()||state.candidate;state.code=document.getElementById("code")?.value.trim()||state.code;if(!state.candidate)return alert("Hãy nhập họ tên trước.");localStorage.setItem("study_candidate",state.candidate);localStorage.setItem("study_code",state.code);state.subject=s;state.page="subject";render()}
function startExam(id){state.exam=exams.find(e=>String(e.id)===String(id));if(!state.exam)return alert("Không tìm thấy bài kiểm tra.");if(!state.exam.questions.length)return alert("Bài này chưa có câu hỏi.");state.answers={};state.startedAt=Date.now();state.page="exam";render();startTimer()}
function startTimer(){clearInterval(state.timer);state.timer=setInterval(updateTimer,1000);updateTimer()}
function updateTimer(){if(state.page!=="exam")return clearInterval(state.timer);const left=Math.max(0,Number(state.exam.duration||0)*60-Math.floor((Date.now()-state.startedAt)/1000));const el=document.getElementById("timer");if(el)el.textContent=`⏱ ${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`;if(left<=0)submitExam(true)}
function examPage(){const qs=state.exam.questions||[];return `<main class="container"><div class="timer" id="timer">⏱ --:--</div><div class="card"><h1>${esc(state.exam.title)}</h1><p class="muted">Thí sinh: <b>${esc(state.candidate)}</b> · ${qs.length} câu</p>${qs.map(renderQuestion).join("")}<button class="btn" onclick="submitExam(false)">NỘP BÀI</button></div></main>`}
function renderQuestion(q,i){const type=q.type||"mcq";if(type==="true_false")return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b>${(q.statements||[]).map((s,j)=>`<div class="option"><span>${String.fromCharCode(97+j)}. ${esc(s)}</span><label><input type="radio" name="q${i}_${j}" onchange="setTF(${i},${j},true)"> Đúng</label><label><input type="radio" name="q${i}_${j}" onchange="setTF(${i},${j},false)"> Sai</label></div>`).join("")}</div>`;if(type==="short")return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b><div style="display:flex;gap:6px;margin-top:10px">${[0,1,2,3].map(j=>`<input maxlength="1" inputmode="text" style="width:48px;text-align:center" oninput="setShort(${i},${j},this.value)" value="${esc((state.answers[i]?.[j]||"))}">`).join("")}</div></div>`;return `<div class="q"><b>Câu ${i+1}. ${esc(q.q||"")}</b>${(q.opts||[]).slice(0,4).map((o,j)=>`<label class="option"><input type="radio" name="q${i}" onchange="state.answers[${i}]=${j}"> ${String.fromCharCode(65+j)}. ${esc(o)}</label>`).join("")}</div>`}
function setTF(i,j,v){if(!Array.isArray(state.answers[i]))state.answers[i]=[];state.answers[i][j]=v}
function setShort(i,j,v){if(!Array.isArray(state.answers[i]))state.answers[i]=["","","",""];state.answers[i][j]=v}
function answerIsCorrect(q,a){if(q.type==="true_false"){const r=q.answers||[];return r.length===4&&r.every((v,j)=>a?.[j]===v)}if(q.type==="short")return String((a||[]).join("")).trim().toLowerCase()===String(q.answer??"").trim().toLowerCase();return Number(a)===Number(q.a)}
async function submitExam(auto=false){if(!state.exam)return;clearInterval(state.timer);const qs=state.exam.questions||[];let correct=0;const wrong=[];qs.forEach((q,i)=>{if(answerIsCorrect(q,state.answers[i]))correct++;else wrong.push(i)});const total=qs.length,score=total?Math.round(correct/total*100):0;const answers=JSON.parse(JSON.stringify(state.answers));const result={examId:state.exam.id,examTitle:state.exam.title,candidate:state.candidate,score,correct,total,timeSec:Math.min(Math.floor((Date.now()-state.startedAt)/1000),Number(state.exam.duration||0)*60),auto,wrongIndexes:wrong,answers};try{await loadSupabase();const {data,error}=await db.from("user_attempts").insert({device_id:deviceId(),exam_id:state.exam.id,exam_title:state.exam.title,student_name:state.candidate,student_code:state.code||null,score,correct,total,duration_seconds:result.timeSec,auto_submitted:auto,answers,wrong_indexes:wrong,reviewed_indexes:[]}).select().single();if(error)throw error;result.id=data.id;await db.from("participants").upsert({name:state.candidate,code:state.code||deviceId()},{onConflict:"code"})}catch(e){console.warn("Không lưu lịch sử Supabase",e)}state.lastResult=result;await loadHistory();state.page="result";render()}
function resultPage(){const r=state.lastResult;return `<main class="container"><div class="card"><h1>🎉 Hoàn thành</h1><p style="text-align:center">${esc(r.candidate)} · ${esc(r.examTitle)}</p><div class="score">${r.score}%</div><p style="text-align:center">Đúng <b>${r.correct}/${r.total}</b> câu</p><p style="text-align:center">${r.auto?"⏰ Hết giờ, hệ thống tự nộp bài.":"Bài đã được nộp thành công."}</p><div style="text-align:center">${r.wrongIndexes?.length?`<button class="btn" onclick="openReview('${r.id||""}')">🧠 Ôn lại ${r.wrongIndexes.length} câu sai</button>`:"<p class="success">🎉 Không có câu sai.</p>"}<button class="btn secondary" onclick="go('history')">Xem lịch sử</button></div></div></main>`}
function historyPage(){const rs=state.history||[];return `<main class="container"><div class="card"><h1>📊 Lịch sử của tôi</h1><p class="muted">Lịch sử được gắn với thiết bị này nên thoát web rồi quay lại vẫn còn.</p>${rs.length?rs.map(r=>`<div class="exam"><div><b>${esc(r.exam_title)}</b><div class="muted">${esc(r.student_name)} · ${new Date(r.created_at).toLocaleString("vi-VN")}</div><div class="muted">${r.correct}/${r.total} câu · ${r.score}%</div></div><div><button class="btn" onclick="openHistory('${r.id}')">Xem</button>${Array.isArray(r.wrong_indexes)&&r.wrong_indexes.length?`<button class="btn secondary" onclick="openReview('${r.id}')">Ôn câu sai</button>`:""}</div></div>`).join(""):"<p class='muted'>Chưa có lượt làm bài.</p>"}</div></main>`}
function openHistory(id){const r=state.history.find(x=>String(x.id)===String(id));if(!r)return;state.lastResult={...r,wrongIndexes:r.wrong_indexes||[]};state.page="result";render()}
async function openReview(id){const r=state.history.find(x=>String(x.id)===String(id))||state.lastResult;if(!r)return;const exam=exams.find(e=>String(e.id)===String(r.exam_id||r.examId))||exams.find(e=>e.title===r.exam_title||e.title===r.examTitle);if(!exam)return alert("Không tìm thấy đề gốc để ôn lại.");state.review={attempt:r,exam,items:(r.wrong_indexes||r.wrongIndexes||[]).map(i=>({index:i,question:exam.questions[i],answer:r.answers?.[i]})),cursor:0};state.page="review";render()}
function reviewPage(){const x=state.review;if(!x||!x.items.length)return `<main class="container"><div class="card"><h2>🎉 Không còn câu sai</h2><button class="btn" onclick="go('history')">Quay lại</button></div></main>`;const item=x.items[x.cursor];const q=item.question;return `<main class="container"><div class="card"><h1>🧠 Ôn lại câu sai</h1><p class="muted">Câu ${x.cursor+1}/${x.items.length}</p><div class="q"><b>${esc(q.q||"")}</b>${q.type==="mcq"?(q.opts||[]).map((o,j)=>`<label class="option"><input type="radio" name="reviewQ" onchange="state.reviewChoice=${j}"> ${String.fromCharCode(65+j)}. ${esc(o)}</label>`).join(""):q.type==="short"?`<input id="reviewShort" maxlength="4" placeholder="Nhập đáp án">`:((q.statements||[]).map((s,j)=>`<div class="option">${String.fromCharCode(97+j)}. ${esc(s)} <select onchange="setReviewTF(${j},this.value)"><option value="">--</option><option value="true">Đúng</option><option value="false">Sai</option></select></div>`).join(""))}</div><button class="btn" onclick="checkReview()">Kiểm tra</button><button class="btn secondary" onclick="go('history')">Thoát</button><div id="reviewMsg"></div></div></main>`}
function setReviewTF(j,v){if(!state.reviewTF)state.reviewTF=[];state.reviewTF[j]=v==="true"}
async function checkReview(){const x=state.review,item=x.items[x.cursor],q=item.question;let ok=false;if(q.type==="mcq")ok=Number(state.reviewChoice)===Number(q.a);else if(q.type==="short")ok=document.getElementById("reviewShort")?.value.trim().toLowerCase()===String(q.answer||"").trim().toLowerCase();else ok=(q.answers||[]).every((v,j)=>state.reviewTF?.[j]===v);const msg=document.getElementById("reviewMsg");if(ok){msg.innerHTML=`<p class="success">✅ Đúng! ${esc(q.explanation||"")}</p>`;const idx=item.index;try{await loadSupabase();const next=[...(item.attempt.reviewed_indexes||[]),idx].filter((v,i,a)=>a.indexOf(v)===i);await db.from("user_attempts").update({reviewed_indexes:next}).eq("id",item.attempt.id)}catch{}setTimeout(()=>{x.cursor++;state.reviewChoice=null;state.reviewTF=[];if(x.cursor>=x.items.length)alert("🎉 Bạn đã ôn xong các câu sai!");state.page=x.cursor<x.items.length?"review":"history";render()},700)}else msg.innerHTML=`<p class="danger-text">❌ Chưa đúng. ${esc(q.explanation||"Hãy xem lại kiến thức rồi thử lại.")}</p>`}
async function ensureThread(){if(state.thread)return state.thread;await loadSupabase();let {data}=await db.from("support_threads").select("*").eq("device_id",deviceId()).maybeSingle();if(!data){const r=await db.from("support_threads").insert({device_id:deviceId(),student_name:state.candidate||localStorage.getItem("study_candidate")||"Người dùng"}).select().single();data=r.data}state.thread=data;return data}
async function loadMessages(){try{const t=await ensureThread();const {data}=await db.from("support_messages").select("*").eq("thread_id",t.id).order("created_at",{ascending:true});state.messages=data||[]}catch(e){console.warn(e);state.messages=[]}}
async function sendSupport(){const input=document.getElementById("supportInput");const text=input?.value.trim();if(!text)return;const t=await ensureThread();await loadSupabase();await db.from("support_messages").insert({thread_id:t.id,sender:"user",message:text});input.value="";await loadMessages();render()}
function supportPage(){return `<main class="container"><div class="card"><h1>💬 Liên hệ Admin</h1><p class="muted">Mã thiết bị: ${esc(deviceId().slice(0,8))} · Tin nhắn được lưu lại.</p><div style="display:grid;gap:8px;max-height:420px;overflow:auto;margin:14px 0">${(state.messages||[]).map(m=>`<div style="padding:10px;border-radius:10px;background:${m.sender==="admin"?"#eef6ff":"#f5f5f5"};margin-left:${m.sender==="admin"?"0":"20%"}"><b>${m.sender==="admin"?"Admin":"Bạn"}</b><div>${esc(m.message)}</div><small class="muted">${new Date(m.created_at).toLocaleString("vi-VN")}</small></div>`).join("")||"<p class='muted'>Chưa có tin nhắn.</p>"}</div><div style="display:flex;gap:8px"><input id="supportInput" placeholder="Mô tả lỗi bạn gặp..." onkeydown="if(event.key==='Enter')sendSupport()"><button class="btn" onclick="sendSupport()">Gửi</button></div><button class="btn secondary" onclick="go('home')">Quay lại</button></div></main>`}
async function go(p){state.page=p;if(p==="home")await loadExams();if(p==="history")await loadHistory();if(p==="support")await loadMessages();render()}
async function render(){document.getElementById("app").innerHTML=header()+page()}
state.candidate=localStorage.getItem("study_candidate")||"";state.code=localStorage.getItem("study_code")||"";
(async()=>{await registerDevice();await loadExams();await loadHistory();await render()})();
