/* Admin V2 usability layer: exam preview/editor/delete, bot toggles, learner tracking, AI health. */
(function(){
  var draft=null, draftId=null, draftMeta={};
  var $=function(id){return document.getElementById(id)};
  var esc2=function(v){return String(v??'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})};
  function toast2(t){if(window.toast)return window.toast(t);alert(t)}
  function ensureModal(){
    if($('examEditorModal'))return;
    var m=document.createElement('div');m.id='examEditorModal';m.className='admin-modal hidden';m.innerHTML=`<div class="admin-modal-card exam-editor-card"><div class="admin-modal-head"><div><span class="eyebrow">EXAM WORKSHOP</span><h2 id="examEditorTitle">Xem trước đề</h2><p class="muted">Kiểm tra và sửa thủ công trước khi phát hành.</p></div><button class="icon-btn" type="button" id="closeExamEditor">×</button></div><div id="examEditorBody" class="exam-editor-body"></div><div class="admin-modal-foot"><button class="soft-btn" id="addQuestionBtn">＋ Thêm câu</button><span></span><button class="soft-btn" id="cancelExamEditor">Đóng</button><button class="primary" id="saveExamEditor">💾 Lưu đề</button></div></div>`;document.body.appendChild(m);
    $('closeExamEditor').onclick=closeEditor;$('cancelExamEditor').onclick=closeEditor;$('addQuestionBtn').onclick=function(){if(!draft)draft=[];draft.push({type:'mcq',q:'',opts:['','','',''],a:0,explanation:''});renderEditor()};$('saveExamEditor').onclick=saveEditor;
  }
  function closeEditor(){$('examEditorModal')?.classList.add('hidden')}
  function normalizeQuestion(q){
    q=q||{};var type=q.type||'mcq';
    if(type==='true_false')return {type:'true_false',q:String(q.q||''),statements:(q.statements||['','','','']).slice(0,4).concat(['','','','']).slice(0,4),answers:(q.answers||[false,false,false,false]).slice(0,4),explanation:String(q.explanation||'')};
    if(type==='short')return {type:'short',q:String(q.q||''),answer:String(q.answer??''),explanation:String(q.explanation||'')};
    return {type:'mcq',q:String(q.q||''),opts:(q.opts||['','','','']).slice(0,4).concat(['','','','']).slice(0,4),a:Number(q.a||0),explanation:String(q.explanation||'')};
  }
  function renderEditor(){
    var box=$('examEditorBody');if(!box||!draft)return;
    box.innerHTML=draft.map(function(q,i){q=normalizeQuestion(q);draft[i]=q;var html=`<article class="editor-question" data-q="${i}"><div class="editor-q-head"><b>Câu ${i+1}</b><select class="editor-type"><option value="mcq" ${q.type==='mcq'?'selected':''}>Trắc nghiệm</option><option value="true_false" ${q.type==='true_false'?'selected':''}>Đúng / Sai</option><option value="short" ${q.type==='short'?'selected':''}>Trả lời ngắn</option></select><button class="danger-btn editor-remove" type="button">Xoá câu</button></div><label>Câu hỏi<textarea class="editor-question-text">${esc2(q.q)}</textarea></label>`;
      if(q.type==='mcq')html+=`<div class="editor-options">${q.opts.map(function(o,j){return `<label>Đáp án ${String.fromCharCode(65+j)}<input class="editor-opt" value="${esc2(o)}"></label>`}).join('')}</div><label>Đáp án đúng<select class="editor-answer">${q.opts.map(function(o,j){return `<option value="${j}" ${Number(q.a)===j?'selected':''}>${String.fromCharCode(65+j)}</option>`}).join('')}</select></label>`;
      else if(q.type==='true_false')html+=`<div class="editor-options">${q.statements.map(function(s,j){return `<label>${String.fromCharCode(97+j)}<input class="editor-statement" value="${esc2(s)}"></label><label class="tf-row"><span>Đáp án</span><select class="editor-tf"><option value="false" ${!q.answers[j]?'selected':''}>Sai</option><option value="true" ${q.answers[j]?'selected':''}>Đúng</option></select></label>`}).join('')}</div>`;
      else html+=`<label>Đáp án đúng<input class="editor-short-answer" value="${esc2(q.answer)}"></label>`;
      html+=`<label>Giải thích<textarea class="editor-explanation">${esc2(q.explanation)}</textarea></label></article>`;return html;}).join('');
    box.querySelectorAll('.editor-type').forEach(function(s){s.onchange=function(){var i=Number(s.closest('.editor-question').dataset.q);draft[i].type=s.value;renderEditor()}});
    box.querySelectorAll('.editor-remove').forEach(function(b){b.onclick=function(){var i=Number(b.closest('.editor-question').dataset.q);draft.splice(i,1);renderEditor()}});
  }
  function readEditor(){
    var rows=[...document.querySelectorAll('.editor-question')];draft=rows.map(function(row){var type=row.querySelector('.editor-type').value,q={type:type,q:row.querySelector('.editor-question-text').value,explanation:row.querySelector('.editor-explanation').value};if(type==='mcq'){q.opts=[...row.querySelectorAll('.editor-opt')].map(function(x){return x.value});q.a=Number(row.querySelector('.editor-answer').value)}else if(type==='true_false'){q.statements=[...row.querySelectorAll('.editor-statement')].map(function(x){return x.value});q.answers=[...row.querySelectorAll('.editor-tf')].map(function(x){return x.value==='true'})}else q.answer=row.querySelector('.editor-short-answer').value;return q});return draft}
  function openEditor(questions,meta,id){ensureModal();draft=(questions||[]).map(normalizeQuestion);draftMeta=meta||{};draftId=id||null;$('examEditorTitle').textContent=draftId?'Chỉnh sửa đề':'Xem trước đề';$('examEditorModal').classList.remove('hidden');renderEditor()}
  async function saveEditor(){try{readEditor();if(!draft.length)return toast2('Đề phải có ít nhất 1 câu.');await loadSupabase();var payload={title:draftMeta.title||'Bài kiểm tra',subject:draftMeta.subject||'Toán',difficulty:draftMeta.difficulty||'Trung bình',duration:Number(draftMeta.duration||45),question_count:draft.length,questions:draft,status:'active'};var result=draftId?await db.from('exams').update(payload).eq('id',draftId):await db.from('exams').insert(payload);if(result.error)throw result.error;closeEditor();toast2(draftId?'Đã cập nhật đề.':'Đã lưu đề sau khi xem trước.');await window.renderTests();window.loadDashboard?.()}catch(e){toast2('Không lưu được đề: '+e.message)}}

  async function createExamPreview(){
    var files=[...($('file')?.files||[])],msg=$('msg');var title=$('title')?.value.trim(),subject=$('subject')?.value,difficulty=$('level')?.value,duration=Number($('minutes')?.value||45),questionCount=Number($('questions')?.value||20),types=[...document.querySelectorAll('input[name="questionType"]:checked')].map(function(x){return x.value});
    if(!files.length)return msg.textContent='⚠️ Hãy chọn ít nhất một tài liệu.';if(!title)return msg.textContent='⚠️ Hãy đặt tên bài.';if(!types.length)return msg.textContent='⚠️ Chọn ít nhất một dạng câu.';
    try{msg.textContent='⏳ Đang đọc tài liệu...';var parts=[];for(var f of files){var text=await extractDoc(f).catch(function(){return ''});if(text)parts.push(`--- ${f.name} ---\n${text}`)}var documentText=parts.join('\n\n').slice(0,220000);if(!documentText)throw new Error('Không trích xuất được chữ từ tài liệu.');msg.textContent='⏳ Gemini đang tạo đề...';var r=await fetch('/api/generate-exam',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fileName:files.map(function(f){return f.name}).join(', '),mimeType:files[0].type,documentText,fileData:'',subject,difficulty,questionCount,types})});var data=await r.json().catch(function(){return {}});if(!r.ok)throw new Error(data.error||'Không tạo được đề');openEditor(data.questions||[],{title,subject,difficulty,duration},null);msg.textContent='✅ Đã tạo bản nháp. Kiểm tra/sửa rồi bấm Lưu đề.';
    }catch(e){msg.textContent='❌ '+e.message}
  }

  async function editSavedExam(id){try{await loadSupabase();var r=await db.from('exams').select('*').eq('id',id).single();if(r.error)throw r.error;openEditor(r.data.questions||[],{title:r.data.title,subject:r.data.subject,difficulty:r.data.difficulty,duration:r.data.duration},r.data.id)}catch(e){toast2(e.message)}}
  async function deleteExam(id,title){if(!confirm(`Xoá bài “${title}”? Thao tác này không thể hoàn tác.`))return;try{var r=await fetch('/api/admin-delete-exam',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(sessionStorage.getItem('study_admin_session_v2')||'')},body:JSON.stringify({id:id})});var d=await r.json().catch(function(){return {}});if(!r.ok)throw new Error(d.error||'Không xoá được bài');toast2('Đã xoá bài kiểm tra.');await window.renderTests()}catch(e){toast2('Không xoá được: '+e.message+' — kiểm tra SUPABASE_SERVICE_ROLE_KEY trên Vercel.')}}
  window.renderTests=async function(){var box=$('testList');if(!box)return;try{await loadSupabase();var r=await db.from('exams').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;box.innerHTML=(r.data||[]).map(function(t){return `<div class="exam-admin-row"><div class="row-meta"><b>${esc2(t.title||'Chưa đặt tên')}</b><small>${esc2(t.subject||'—')} · ${Number(t.question_count||t.questions?.length||0)} câu · ${Number(t.duration||0)} phút · ${esc2(t.status||'active')}</small></div><div class="row-actions"><button class="soft-btn" data-exam-view="${t.id}">👁 Xem/Sửa</button><button class="danger-btn" data-exam-delete="${t.id}" data-exam-title="${esc2(t.title||'Chưa đặt tên')}">🗑 Xoá</button></div></div>`}).join('')||`<p class="muted">Chưa có bài kiểm tra.</p>`;box.querySelectorAll('[data-exam-view]').forEach(function(b){b.onclick=function(){editSavedExam(b.dataset.examView)}});box.querySelectorAll('[data-exam-delete]').forEach(function(b){b.onclick=function(){deleteExam(b.dataset.examDelete,b.dataset.examTitle)}})}catch(e){box.innerHTML=`<p class="danger-text">${esc2(e.message)}</p>`}};

  window.loadAccounts=async function(){try{await loadSupabase();var r=await db.from('support_accounts').select('*').order('created_at',{ascending:true});if(r.error)throw r.error;admin.accounts=r.data||[];var list=$('accountList');if(list)list.innerHTML=admin.accounts.map(function(a){return `<div class="account-row"><div class="row-meta"><b>${esc2(a.avatar||'💬')} ${esc2(a.name)}</b><small>@${esc2(a.handle||'—')} · ${esc2(a.description||'')}</small></div><div class="row-actions"><button class="bot-toggle ${a.bot_enabled?'on':'off'}" data-account-toggle="${a.id}">🤖 Bot ${a.bot_enabled?'ON':'OFF'}</button></div></div>`}).join('')||`<p class="muted">Chưa có tài khoản hỗ trợ.</p>`;var sel=$('botAccount');if(sel)sel.innerHTML=admin.accounts.map(function(a){return `<option value="${a.id}">${esc2(a.avatar||'💬')} ${esc2(a.name)}</option>`}).join('');list?.querySelectorAll('[data-account-toggle]').forEach(function(b){b.onclick=async function(){var a=admin.accounts.find(function(x){return String(x.id)===String(b.dataset.accountToggle)});if(!a)return;var u=await db.from('support_accounts').update({bot_enabled:!a.bot_enabled,updated_at:new Date().toISOString()}).eq('id',a.id);if(u.error)return toast2(u.error.message);a.bot_enabled=!a.bot_enabled;await loadAccounts();toast2('Đã '+(a.bot_enabled?'bật':'tắt')+' bot cho '+a.name)}})}catch(e){toast2('Không tải được tài khoản hỗ trợ: '+e.message)}};

  async function showPerson(idOrCode){await loadSupabase();var ps=await db.from('participants').select('*');var as=await db.from('user_attempts').select('*').order('created_at',{ascending:false});var p=(ps.data||[]).find(function(x){return String(x.id)===String(idOrCode)||String(x.code||'')===String(idOrCode)});var code=p?.code||idOrCode;var rows=(as.data||[]).filter(function(a){return String(a.student_code||a.device_id||'')===String(code)});ensureModal();var m=$('examEditorModal');$('examEditorTitle').textContent='Theo dõi người tham gia';$('examEditorBody').innerHTML=`<div class="person-summary"><h3>${esc2(p?.name||'Người tham gia')}</h3><p class="muted">Mã: ${esc2(code)} · ${rows.length} lượt làm</p></div><div class="person-attempts">${rows.map(function(r){return `<div class="person-attempt"><div><b>${esc2(r.exam_title||'Bài kiểm tra')}</b><small>${esc2(r.created_at?new Date(r.created_at).toLocaleString('vi-VN'):'')}</small></div><span class="badge">${Number(r.score||0)}% · ${Number(r.correct||0)}/${Number(r.total||0)}</span><button class="soft-btn" data-attempt="${r.id}">Xem</button></div>`}).join('')||'<p class="muted">Chưa có lượt làm.</p>'}</div>`;m.classList.remove('hidden');$('saveExamEditor').classList.add('hidden');$('addQuestionBtn').classList.add('hidden');$('cancelExamEditor').textContent='Đóng';$('examEditorBody').querySelectorAll('[data-attempt]').forEach(function(b){b.onclick=function(){var r=(as.data||[]).find(function(x){return String(x.id)===String(b.dataset.attempt)});if(!r)return;alert(JSON.stringify({bai:r.exam_title,diem:r.score,correct:r.correct,total:r.total,cauSai:r.wrong_indexes},null,2))}})}
  window.loadParticipants=async function(){var box=$('participantRows');if(!box)return;try{await loadSupabase();var ps=await db.from('participants').select('*').order('created_at',{ascending:false});var as=await db.from('user_attempts').select('*').order('created_at',{ascending:false});if(ps.error)throw ps.error;if(as.error)throw as.error;box.innerHTML=(ps.data||[]).map(function(p){var rows=(as.data||[]).filter(function(a){return String(a.student_code||a.device_id||'')===String(p.code||'')});var latest=rows[0];return `<tr class="clickable-row" data-person="${esc2(p.code||p.id)}"><td><b>${esc2(p.name||'Không tên')}</b></td><td>${esc2(p.code||'—')}</td><td>${rows.length}</td><td><span class="badge">${latest?Number(latest.score||0)+'%':'—'}</span></td><td>${latest?esc2(new Date(latest.created_at).toLocaleString('vi-VN')):'—'}</td></tr>`}).join('')||`<tr><td colspan="5">Chưa có người tham gia.</td></tr>`;box.querySelectorAll('[data-person]').forEach(function(row){row.onclick=function(){showPerson(row.dataset.person)}})}catch(e){box.innerHTML=`<tr><td colspan="5" class="danger-text">${esc2(e.message)}</td></tr>`}};
  window.loadHistory=async function(){var box=$('historyRows');if(!box)return;try{await loadSupabase();var r=await db.from('user_attempts').select('*').order('created_at',{ascending:false}).limit(300);if(r.error)throw r.error;box.innerHTML=(r.data||[]).map(function(x){return `<tr class="clickable-row" data-history="${x.id}"><td>${esc2(x.created_at?new Date(x.created_at).toLocaleString('vi-VN'):'—')}</td><td><b>${esc2(x.student_name||'Không tên')}</b><small>${esc2(x.student_code||String(x.device_id||'').slice(0,8))}</small></td><td>${esc2(x.exam_title||'—')}</td><td><span class="badge">${Number(x.score||0)}% · ${Number(x.correct||0)}/${Number(x.total||0)}</span></td><td>${Array.isArray(x.wrong_indexes)?x.wrong_indexes.length:'—'}</td></tr>`}).join('')||`<tr><td colspan="5">Chưa có lịch sử.</td></tr>`;box.querySelectorAll('[data-history]').forEach(function(row){row.onclick=function(){var x=(r.data||[]).find(function(v){return String(v.id)===String(row.dataset.history)});if(x)showPerson(x.student_code||x.device_id)}})}catch(e){box.innerHTML=`<tr><td colspan="5" class="danger-text">${esc2(e.message)}</td></tr>`}};

  function addAIHealth(){var tab=$('assistant');if(!tab||tab.querySelector('.ai-health'))return;var host=tab.querySelector('.section-head');if(!host)return;var p=document.createElement('div');p.className='panel ai-health';p.innerHTML=`<div class="panel-head"><div><h3>🧠 AI & Bảo trì hệ thống</h3><small>Kiểm tra nhanh trước khi sửa lỗi hoặc nâng cấp.</small></div><button class="soft-btn" id="runHealth">Kiểm tra</button></div><div class="ai-health-actions"><button class="soft-btn" data-prompt="Kiểm tra toàn bộ lỗi có thể xảy ra ở chat hỗ trợ và đề xuất cách xử lý.">🔎 Chẩn đoán chat</button><button class="soft-btn" data-prompt="Kiểm tra UX/UI hiện tại và đề xuất 5 tinh chỉnh có tác động lớn nhưng ít rủi ro.">🎨 Audit giao diện</button><button class="soft-btn" data-prompt="Lập checklist bảo trì STUDY: Vercel, Supabase, Gemini, realtime và dữ liệu bài kiểm tra.">🛠 Bảo trì</button></div><div id="healthResult" class="muted">Chưa kiểm tra.</div></div>`;tab.querySelector('.section-head').after(p);p.querySelector('#runHealth').onclick=async function(){var b=p.querySelector('#healthResult');b.textContent='Đang kiểm tra...';try{var r=await fetch('/api/admin-health',{headers:{Authorization:'Bearer '+(sessionStorage.getItem('study_admin_session_v2')||'')}});var d=await r.json();if(!r.ok)throw new Error(d.error||'Health check lỗi');b.innerHTML=`<div class="health-grid">${Object.entries(d.checks||{}).map(function(x){return `<span class="health-item ${x[1]?'ok':'bad'}">${x[1]?'✓':'!'} ${esc2(x[0])}</span>`}).join('')}</div>`}catch(e){b.textContent='⚠️ '+e.message}};p.querySelectorAll('[data-prompt]').forEach(function(b){b.onclick=function(){openTab('assistant');var input=$('assistantInput');if(input){input.value=b.dataset.prompt;input.focus()}}})}

  function bindEnhancements(){ensureModal();var c=$('createBtn');if(c)c.onclick=createExamPreview;var r=$('reloadTests');if(r)r.onclick=window.renderTests;addAIHealth();}
  function boot(){setTimeout(bindEnhancements,350);setTimeout(bindEnhancements,1200)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
