/* STUDY TH — lightweight Admin bootstrap. */
(function(){
  'use strict';
  if(window.__studyLoginBootstrapV9)return;
  window.__studyLoginBootstrapV9=true;
  const TOKEN_KEY='study_admin_session_v2';
  const CRITICAL_SCRIPT='auth.js?v=20260915-3';
  const APP_SCRIPT='app.js?v=20260915-3';
  const TITLES={dashboard:'Tổng quan',support:'Hỗ trợ',participants:'Người tham gia',history:'Lịch sử làm bài',tests:'Bài kiểm tra',accounts:'Tài khoản hỗ trợ',bot:'Bot tự động',assistant:'Admin Copilot'};
  const LOADERS={dashboard:'loadDashboard',support:'startSupportLive',participants:'loadParticipants',history:'loadHistory',tests:'renderTests',accounts:'loadAccounts',bot:'loadBotRules',assistant:'loadAssistant'};
  const $=id=>document.getElementById(id);
  const loaded=new Map();
  const moduleMap={tests:['exam-builder-v3.js?v=20260916-1'],support:[],participants:[],history:[],accounts:[],bot:[],assistant:[]};

  function injectMobileUX(){if($('study-mobile-ux'))return;const s=document.createElement('style');s.id='study-mobile-ux';s.textContent=`
@media(max-width:760px){html,body{width:100%;max-width:100%;overflow-x:hidden}.admin-shell{min-width:0;width:100%}.sidebar{position:fixed;z-index:70;left:0;top:0;bottom:0;width:64px;height:100dvh;padding:9px 6px;overflow:hidden}.sidebar-top{padding:2px 0 10px;display:grid;gap:7px;justify-items:center}.brand-row{justify-content:center}.brand-row>div{display:none}.brand-orb{width:42px;height:42px;border-radius:14px}.sidebar-top .icon-btn{width:38px;height:38px}.admin-profile{justify-content:center;margin:2px 0 9px;padding:10px 2px}.admin-profile>div{display:none}.online-dot{width:8px;height:8px}#adminNav{gap:4px}.nav-item{width:52px;min-height:46px;padding:9px 2px;justify-content:center;gap:0;text-align:center;font-size:19px;transform:none!important}.nav-item span{display:none}.nav-item i{position:absolute;right:0;top:1px;min-width:16px;height:16px;padding:0 3px;font-size:9px}.sidebar-bottom{gap:4px}.workspace{width:calc(100% - 64px);margin-left:64px;padding:14px 9px 30px;min-width:0}.topbar{margin-bottom:12px}.topbar h1{font-size:22px}.live-pill{padding:7px 8px}.hero{min-height:auto;padding:18px;border-radius:18px}.hero h2{font-size:22px}.hero p{font-size:13px;line-height:1.45}.hero-orb{width:56px;height:56px;border-radius:18px;font-size:24px}.stats-grid{grid-template-columns:1fr 1fr;gap:8px}.stat-card{padding:13px;border-radius:15px}.stat-card b{font-size:23px;margin-top:6px}.two-col,.form-grid{grid-template-columns:1fr}.panel{padding:13px;border-radius:16px}.section-head{align-items:flex-start}.section-head h2{font-size:22px}.section-head p{font-size:13px;line-height:1.4}.quick-grid{grid-template-columns:1fr 1fr;gap:8px}.quick{padding:11px}.messenger{height:calc(100dvh - 150px);min-height:0;grid-template-columns:1fr}.conversation-list{display:none}.table-wrap{width:100%;overflow-x:auto}.eb2-panel{padding:14px!important;border-radius:18px!important}.eb2-mode{grid-template-columns:1fr!important}.eb2-head{display:block!important}.eb2-grid{grid-template-columns:1fr!important}.eb2-field.full{grid-column:auto!important}.eb2-file{min-width:0}.eb2-file-name{font-size:12px}.eb2-field input,.eb2-field select,.eb2-field textarea{font-size:16px!important}.eb2-actions{display:grid!important;grid-template-columns:1fr 1fr;gap:8px}.eb2-actions button{min-height:46px;width:100%}.assistant-messages{height:calc(100dvh - 300px)!important}.composer textarea{font-size:16px}.send-btn{width:40px;height:40px}}
@media(max-width:420px){.sidebar{width:58px}.workspace{width:calc(100% - 58px);margin-left:58px;padding:12px 6px 28px}.nav-item{width:48px}.quick-grid{grid-template-columns:1fr}.eb2-actions{grid-template-columns:1fr}.top-actions .live-pill{display:none}}
`;document.head.appendChild(s)}
  function repairLogin(){const screen=$('adminLogin'),form=$('loginForm'),input=$('adminPassword'),btn=form?.querySelector('button[type="submit"]');if(!screen||!form||!input||!btn)return;screen.style.pointerEvents='auto';form.style.pointerEvents='auto';input.style.pointerEvents='auto';btn.style.pointerEvents='auto'}
  function setAuthenticatedView(){const screen=$('adminLogin'),app=$('adminApp');if(screen){screen.classList.add('hidden');screen.style.setProperty('display','none','important');screen.style.setProperty('visibility','hidden','important');screen.style.setProperty('pointer-events','none','important')}if(app){app.classList.remove('hidden');app.style.setProperty('display','flex','important');app.style.setProperty('visibility','visible','important');app.style.setProperty('pointer-events','auto','important')}}
  function openTab(id){if(!TITLES[id])return;const app=$('adminApp'),tab=$(id);if(!app||!tab)return;window.admin=window.admin||{};admin.tab=id;app.querySelectorAll('.workspace > .tab').forEach(x=>x.classList.toggle('active',x===tab));app.querySelectorAll('#adminNav .nav-item[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const title=$('pageTitle');if(title)title.textContent=TITLES[id];requestAnimationFrame(()=>{const loader=LOADERS[id];try{if(loader&&typeof window[loader]==='function')window[loader]()}catch(e){console.warn('[STUDY tab loader]',id,e)}loadTabModules(id)})}
  window.openTab=openTab;
  function bindNavigation(){const nav=$('adminNav');if(nav&&!nav.__studyBound){nav.__studyBound=true;nav.addEventListener('click',function(e){const b=e.target.closest('button[data-tab]');if(!b||!nav.contains(b))return;e.preventDefault();e.stopPropagation();openTab(b.dataset.tab)})}document.querySelectorAll('.quick[data-go]').forEach(b=>{if(!b.__studyBound){b.__studyBound=true;b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openTab(b.dataset.go)})}})}
  function loadScript(src){if(loaded.has(src))return loaded.get(src);const p=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error('Không tải được '+src));document.body.appendChild(s)});loaded.set(src,p);return p}
  async function loadTabModules(id){for(const src of moduleMap[id]||[]){try{await loadScript(src)}catch(e){console.warn('[STUDY module]',e.message)}}}
  async function startAdmin(){if(window.__studyAdminStarted)return;window.__studyAdminStarted=true;try{await loadScript(CRITICAL_SCRIPT);await loadScript(APP_SCRIPT);setAuthenticatedView();injectMobileUX();bindNavigation();if(typeof window.bootAdmin==='function'){try{await window.bootAdmin()}catch(e){console.warn('[STUDY boot]',e)}}}catch(e){window.__studyAdminStarted=false;console.error('[STUDY bootstrap]',e);setAuthenticatedView();injectMobileUX();bindNavigation()}}
  async function authenticate(event){event?.preventDefault();event?.stopImmediatePropagation();const form=$('loginForm'),input=$('adminPassword'),btn=form?.querySelector('button[type="submit"]');if(!form||!input||!btn||form.__loginBusy)return;form.__loginBusy=true;repairLogin();const password=String(input.value||'');if(!password){const m=$('loginMsg');if(m)m.textContent='⚠️ Vui lòng nhập mật khẩu Admin.';form.__loginBusy=false;input.focus();return}btn.disabled=true;input.disabled=true;btn.textContent='⏳ Đang đăng nhập...';try{const r=await fetch('/api/admin-login',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({password}),cache:'no-store',credentials:'same-origin'});const text=await r.text();let data={};try{data=JSON.parse(text||'{}')}catch{}if(!r.ok)throw new Error(data.error||('Đăng nhập thất bại (HTTP '+r.status+')'));if(!data.token)throw new Error('Máy chủ không trả về session token.');sessionStorage.setItem(TOKEN_KEY,data.token);await startAdmin()}catch(e){const m=$('loginMsg');if(m)m.textContent='❌ '+e.message}finally{form.__loginBusy=false;btn.disabled=false;input.disabled=false;btn.textContent='🔐 Đăng nhập';repairLogin()}}
  function bindLogin(){const form=$('loginForm');if(form&&!form.__studyLoginBound){form.__studyLoginBound=true;form.addEventListener('submit',authenticate,true)}repairLogin()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindLogin,{once:true});else bindLogin();
  if(sessionStorage.getItem(TOKEN_KEY))startAdmin();
})();
