/* Real server-backed maintenance control for Admin Overview. */
(function(){
 if(window.__maintenanceControl)return;window.__maintenanceControl=true;
 const escv=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function buttons(){return [...document.querySelectorAll('button,a,[role="button"]')].filter(x=>/Tạm thời bảo trì STUDY TH|Kiểm tra lại|bảo trì STUDY TH|Khôi phục STUDY TH/i.test(x.textContent||''));}
 async function get(){const r=await fetch('/api/maintenance',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không đọc được trạng thái bảo trì');return d.data||{maintenance:false};}
 function paint(st){buttons().forEach(b=>{const isCheck=/Kiểm tra lại/i.test(b.textContent||'');if(isCheck){b.innerHTML='↻ <span>Kiểm tra lại</span>';b.classList.add('maintenance-check-action');}else{b.innerHTML=st.maintenance?'🟢 <span>Tắt bảo trì STUDY TH</span>':'🔧 <span>Tạm thời bảo trì STUDY TH</span>';b.classList.toggle('maintenance-on',!!st.maintenance);b.classList.add('maintenance-toggle-action');b.title=st.maintenance?'Đang bảo trì — bấm để khôi phục STUDY TH':'Bật chế độ bảo trì cho STUDY TH';}});}
 async function toggle(e){e.preventDefault();e.stopImmediatePropagation();const current=await get();const next=!current.maintenance;const r=await fetch('/api/maintenance',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(typeof token==='function'?token():'')},body:JSON.stringify({maintenance:next})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Không đổi được trạng thái bảo trì.');paint(d.data||{maintenance:next});if(typeof toast==='function')toast(next?'🛠️ STUDY TH đã chuyển sang chế độ bảo trì.':'🟢 Đã tắt bảo trì — STUDY TH hoạt động lại.');}
 async function refresh(){try{const st=await get();paint(st);if(typeof toast==='function')toast(st.maintenance?'🛠️ STUDY TH đang bảo trì.':'🟢 STUDY TH đang hoạt động.');}catch(e){if(typeof toast==='function')toast('❌ '+e.message);}}
 function bind(){buttons().forEach(b=>{if(b.__maintenanceBound)return;b.__maintenanceBound=true;if(/Kiểm tra lại/i.test(b.textContent||''))b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();refresh()},true);else b.addEventListener('click',function(e){toggle(e).catch(err=>{if(typeof toast==='function')toast('❌ '+err.message)})},true);});get().then(paint).catch(()=>{});}
 const css=document.createElement('style');css.textContent='.maintenance-toggle-action,.maintenance-check-action{display:inline-flex!important;align-items:center;justify-content:center;gap:8px;border-radius:14px!important;padding:11px 15px!important;font-weight:750!important;transition:.2s!important}.maintenance-toggle-action{background:linear-gradient(135deg,#7c5cff,#9b7cff)!important;color:#fff!important;box-shadow:0 8px 22px rgba(124,92,255,.22)!important}.maintenance-toggle-action.maintenance-on{background:linear-gradient(135deg,#10b981,#059669)!important}.maintenance-check-action{background:rgba(124,92,255,.09)!important;border:1px solid rgba(124,92,255,.22)!important}.maintenance-toggle-action:hover,.maintenance-check-action:hover{transform:translateY(-1px);filter:brightness(1.04)}';document.head.appendChild(css);
 function boot(){bind();new MutationObserver(bind).observe(document.body,{childList:true,subtree:true});}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
