const ADMIN_MEDIA_BUCKET="support-media";
function toggleAdminPicker(id){document.querySelectorAll(".admin-picker").forEach(x=>x.id!==id&&x.classList.add("hidden"));document.getElementById(id)?.classList.toggle("hidden")}
function insertAdminEmoji(x){const input=document.getElementById("replyInput");if(!input)return;input.value+=(input.value?" ":"")+x;input.focus();document.querySelectorAll(".admin-picker").forEach(p=>p.classList.add("hidden"))}
function adminMediaHtml(m){if(m.sticker)return `<div class="admin-sticker">${esc(m.sticker)}</div>`;if(m.attachment_url&&String(m.attachment_type||"").startsWith("image/"))return `<a href="${esc(m.attachment_url)}" target="_blank" rel="noopener"><img class="admin-attachment" src="${esc(m.attachment_url)}" alt="${esc(m.attachment_name||"Hình ảnh")}" loading="lazy"></a>`;return ""}
function renderChat(){const t=admin.thread;if(!t)return;$("chatHeader").innerHTML=`<div class="chat-person"><span class="avatar">${esc(t.support_accounts?.avatar||"💬")}</span><div><b>${esc(t.student_name||"Người dùng")}</b><small>${esc(t.support_accounts?.name||"Hỗ trợ chung")} · ${esc(String(t.device_id||"").slice(0,12))}</small></div></div>`;$("supportMessages").innerHTML=(admin.messages||[]).map(m=>`<div class="bubble-row ${m.sender||"user"}"><div class="bubble ${m.sender||"user"}"><b>${esc(m.sender_name||(m.sender==="admin"?"Bạn":m.sender==="bot"?"Bot":"Người dùng"))}</b>${adminMediaHtml(m)}${m.message&&!["📷 Hình ảnh","🎞️ GIF","✨ Sticker"].includes(m.message)?`<div>${esc(m.message)}</div>`:""}<small>${m.created_at?esc(new Date(m.created_at).toLocaleString("vi-VN")):""}</small></div></div>`).join("")||`<div class="empty-chat"><span>💬</span><small>Chưa có tin nhắn.</small></div>`;$("replyForm").classList.remove("hidden");const box=$("supportMessages");box.scrollTop=box.scrollHeight}
async function uploadAdminSupportMedia(file){if(!file)return null;if(!file.type.startsWith("image/"))throw new Error("Chỉ nhận ảnh và GIF.");if(file.size>8*1024*1024)throw new Error("Ảnh/GIF tối đa 8MB.");await loadSupabase();const safe=(file.name||"image").replace(/[^a-zA-Z0-9._-]/g,"_");const path=`admin/${Date.now()}-${Math.random().toString(36).slice(2,8)}-${safe}`;const {error}=await db.storage.from(ADMIN_MEDIA_BUCKET).upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return {url:db.storage.from(ADMIN_MEDIA_BUCKET).getPublicUrl(path).data.publicUrl,type:file.type,name:file.name}}
async function sendReplyFile(file){try{if(!admin.thread)throw new Error("Hãy chọn cuộc trò chuyện trước.");const media=await uploadAdminSupportMedia(file);if(!media)return;await loadSupabase();const {error}=await db.from("support_messages").insert({thread_id:admin.thread.id,account_id:admin.thread.account_id||null,sender:"admin",sender_name:"Admin",message:media.type==="image/gif"?"🎞️ GIF":"📷 Hình ảnh",attachment_url:media.url,attachment_type:media.type,attachment_name:media.name});if(error)throw error;toast("Đã gửi file");await openThread(admin.thread.id);await loadSupportThreads()}catch(e){toast("❌ "+e.message)}}
async function sendAdminSticker(sticker){if(!admin.thread)return toast("Hãy chọn cuộc trò chuyện");try{await loadSupabase();const {error}=await db.from("support_messages").insert({thread_id:admin.thread.id,account_id:admin.thread.account_id||null,sender:"admin",sender_name:"Admin",message:"✨ Sticker",sticker});if(error)throw error;document.querySelectorAll(".admin-picker").forEach(x=>x.classList.add("hidden"));await openThread(admin.thread.id);await loadSupportThreads()}catch(e){toast("❌ "+e.message)}}
async function renderTests(){const box=$("testList");if(!box)return;try{await loadSupabase();const {data,error}=await db.from("exams").select("*").order("created_at",{ascending:false});if(error)throw error;box.innerHTML=(data||[]).map(t=>`<div class="account-row"><div class="row-meta"><b>${esc(t.title||"Chưa đặt tên")}</b><small>${esc(t.subject||"—")} · ${Number(t.question_count||0)} câu · ${Number(t.duration||0)} phút · ${esc(t.status||"active")}</small></div><div class="row-actions"><span class="badge">${esc(t.status||"active")}</span><button class="danger-small" type="button" onclick="deleteExam('${t.id}')">🗑️ Xoá</button></div></div>`).join("")||`<p class="muted">Chưa có bài kiểm tra.</p>`}catch(e){box.innerHTML=`<p class="danger-text">${esc(e.message)}</p>`}}
async function deleteExam(id){const row=Array.from(document.querySelectorAll("#testList .account-row")).find(x=>x.querySelector(`button[onclick*="${id}"]`));const title=row?.querySelector(".row-meta b")?.textContent||"Bài kiểm tra";if(!confirm(`Xoá bài “${title}”? Hành động này không thể hoàn tác.`))return;try{const r=await fetch("/api/admin-delete-exam",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()}`},body:JSON.stringify({id})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||"Không xoá được bài");toast("Đã xoá bài kiểm tra");await renderTests();loadDashboard()}catch(e){toast("❌ "+e.message)}}
setTimeout(()=>{if($("reloadTests"))$("reloadTests").onclick=renderTests},0);
