/* STUDY TH — FINAL ADMIN SUPPORT RUNTIME. Single owner, no layout observer. */
(function(){
'use strict';
if(window.__studyAdminSupportFINAL)return;
window.__studyAdminSupportFINAL=true;
var state={threadId:null,busy:false};
var $=function(s,r){return (r||document).querySelector(s)};
var esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})};
var root=function(){return $('#support')};
var active=function(){var x=root();return !!(x&&x.classList.contains('active'))};
async function db(){if(typeof window.loadSupabase!=='function')throw new Error('Supabase chưa sẵn sàng');var d=await window.loadSupabase();if(!d||typeof d.from!=='function')throw new Error('Không kết nối được Supabase');return d;}
function css(){if($('#support-final-runtime-css'))return;var s=document.createElement('style');s.id='support-final-runtime-css';s.textContent='#support.active .messenger{display:grid!important;grid-template-columns:330px minmax(0,1fr)!important;height:min(690px,calc(100dvh - 205px))!important;min-height:0!important;overflow:hidden!important}#support.active .conversation{display:flex!important;flex-direction:column!important;height:100%!important;min-height:0!important;min-width:0!important;overflow:hidden!important}#support.active #chatHeader{display:block!important;flex:0 0 auto!important}#support.active #supportMessages{display:block!important;flex:1 1 auto!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important}#support.active #replyForm{display:flex!important;visibility:visible!important;opacity:1!important;position:relative!important;z-index:99999!important;flex:0 0 auto!important;width:100%!important;min-height:68px!important;height:auto!important;box-sizing:border-box!important;align-items:flex-end!important}#support.active #replyForm.hidden{display:flex!important}#support.active #replyInput{display:block!important;visibility:visible!important;opacity:1!important;flex:1 1 auto!important;width:auto!important;min-width:0!important;height:42px!important;min-height:42px!important}#support.active #replyForm .send-btn{display:grid!important;visibility:visible!important;opacity:1!important;flex:0 0 42px!important;width:42px!important;height:42px!important}@media(max-width:650px){#support.active .messenger{grid-template-columns:1fr!important;grid-template-rows:112px minmax(0,1fr)!important;height:calc(100dvh - 245px)!important}#support.active .conversation-list{height:112px!important;max-height:112px!important}#support.active .conversation{grid-row:2!important}}';document.head.appendChild(s)}
function composer(){var c=$('#support .conversation');if(!c)return null;var f=$('#replyForm',c);if(!f){f=document.createElement('form');f.id='replyForm';f.className='composer';f.autocomplete='off';f.innerHTML='<textarea id="replyInput" rows="1" placeholder="Nhập tin nhắn..."></textarea><button class="send-btn" type="submit">➤</button>';c.appendChild(f)}f.classList.remove('hidden');f.removeAttribute('hidden');var i=$('#replyInput',f);if(!i){i=document.createElement('textarea');i.id='replyInput';i.rows=1;i.placeholder='Nhập tin nhắn...';f.insertBefore(i,f.querySelector('.send-btn'))}if(!f.dataset.boundFinal){f.dataset.boundFinal='1';f.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();send()},true);i.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send()}},true)}return f}
function layout(){css();composer()}
function render(rows){var box=$('#supportMessages');if(!box)return;rows=rows||[];box.innerHTML=rows.length?rows.map(function(m){var mine=String(m.sender||m.sender_role||'')==='admin';var text=m.message!=null?m.message:(m.content!=null?m.content:(m.text||''));return '<div class="message '+(mine?'mine':'theirs')+'"><div class="support-bubble"><b>'+(mine?'Admin':'Người dùng')+'</b><div>'+esc(text).replace(/\n/g,'<br>')+'</div>'+(m.attachment_url?'<div><a href="'+esc(m.attachment_url)+'" target="_blank" rel="noopener">📎 '+esc(m.attachment_name||'Tệp đính kèm')+'</a></div>':'')+'<small>'+esc(m.created_at?new Date(m.created_at).toLocaleString('vi-VN'):'')+'</small></div></div>'}).join(''):'<div class="empty-chat"><span>💬</span><b>Chưa có tin nhắn</b><small>Hãy gửi lời nhắn cho người học.</small></div>';box.scrollTop=box.scrollHeight;layout()}
async function loadThreads(){var box=$('#supportThreads');if(!box)return;try{var d=await db();var r=await d.from('support_threads').select('*').order('updated_at',{ascending:false});if(r.error)throw r.error;var rows=r.data||[];box.innerHTML=rows.length?rows.map(function(t){return '<button type="button" class="thread '+(state.threadId&&String(t.id)===String(state.threadId)?'active':'')+'" data-final-thread="'+esc(t.id)+'"><div class="thread-main"><b>'+esc(t.student_name||t.user_name||'Người dùng')+'</b><small>'+esc(t.last_message||'Cuộc trò chuyện')+'</small></div><span class="badge">'+esc(t.status||'open')+'</span></button>'}).join(''):'<div class="empty-chat"><span>💬</span><b>Chưa có cuộc trò chuyện</b></div>';Array.prototype.forEach.call(box.querySelectorAll('[data-final-thread]'),function(b){b.onclick=function(e){e.preventDefault();openThread(b.getAttribute('data-final-thread'))}})}catch(e){console.error('[support final] threads',e);box.innerHTML='<div class="danger-text">Không đọc được hỗ trợ: '+esc(e.message||e)+'</div>'}layout()}
async function loadMessages(id){state.threadId=String(id);var box=$('#supportMessages');if(box)box.innerHTML='<div class="empty-chat"><span>⏳</span><b>Đang tải tin nhắn...</b></div>';layout();try{var d=await db();var r=await d.from('support_messages').select('*').eq('thread_id',id).order('created_at',{ascending:true});if(r.error)throw r.error;render(r.data||[]);await d.from('support_threads').update({unread_admin:0}).eq('id',id);var btn=Array.prototype.find.call(document.querySelectorAll('#supportThreads [data-final-thread]'),function(x){return String(x.dataset.finalThread)===String(id)});var head=$('#chatHeader');if(head)head.innerHTML='<div class="chat-person"><span class="avatar">💬</span><div><b>'+esc(btn&&$('b',btn)?$('b',btn).textContent:'Người dùng')+'</b><small>Đang trò chuyện với người học</small></div></div>';layout()}catch(e){console.error('[support final] messages',e);if(box)box.innerHTML='<div class="danger-text">Không tải được tin nhắn: '+esc(e.message||e)+'</div>';layout()}}
async function openThread(id){if(!id)return;state.threadId=String(id);await loadMessages(id);await loadThreads();layout();var i=$('#replyInput');if(i)i.focus()}
async function send(){if(state.busy||!state.threadId)return;var i=$('#replyInput');if(!i){layout();i=$('#replyInput')}var text=i&&i.value.trim();if(!text)return;state.busy=true;if(i)i.disabled=true;try{var d=await db();var r=await d.from('support_messages').insert({thread_id:state.threadId,sender:'admin',message:text,bot_handled:false}).select('*').single();if(r.error)throw r.error;i.value='';await loadMessages(state.threadId)}catch(e){console.error('[support final] send',e);alert('Không gửi được trả lời: '+(e.message||e))}finally{state.busy=false;layout();var x=$('#replyInput');if(x){x.disabled=false;x.focus()}}}
window.sendAdminReply=send;window.__studySendSupportTextFINAL=send;window.__studyOpenSupportThread=openThread;
function boot(){layout();var nav=document.querySelector('[data-tab="support"]');if(nav&&!nav.dataset.finalBound){nav.dataset.finalBound='1';nav.addEventListener('click',function(){setTimeout(function(){layout();loadThreads()},80)});}var refresh=$('#newSupportRefresh');if(refresh&&!refresh.dataset.finalBound){refresh.dataset.finalBound='1';refresh.addEventListener('click',function(){loadThreads();if(state.threadId)loadMessages(state.threadId)})}if(active())loadThreads();setInterval(function(){if(active())layout()},2000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
