/* STUDY TH — authoritative Admin support messenger. */
(function(){
'use strict';
if(window.__studyAdminSupportV5)return;window.__studyAdminSupportV5=true;
var adminSupportThread=null,adminSupportRealtime=null,adminSupportPoll=null,loadingThread=false,sendingReply=false;
function escText(v){return typeof window.esc==='function'?window.esc(v):String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function supportActive(){var x=document.getElementById('support');return !!(x&&x.classList.contains('active'))}
function ensureReplyComposer(show){var form=document.getElementById('replyForm');if(!form)return;if(show){form.classList.remove('hidden');form.style.removeProperty('display');form.style.display='flex';form.setAttribute('aria-hidden','false')}else{form.classList.add('hidden');form.style.removeProperty('display');form.setAttribute('aria-hidden','true')}}
async function dbReady(){if(typeof window.loadSupabase!=='function')throw new Error('Supabase chưa sẵn sàng.');var client=await window.loadSupabase();if(!client||typeof client.from!=='function')throw new Error('Không khởi tạo được kết nối dữ liệu.');return client}
async function loadSupportThreads(){var box=document.getElementById('supportThreads');if(!box)return;try{var d=await dbReady(),r=await d.from('support_threads').select('*,support_accounts(name,avatar)').order('updated_at',{ascending:false});if(r.error)throw r.error;var rows=r.data||[];box.innerHTML=rows.length?rows.map(function(t){return '<button type="button" class="test thread" data-support-thread="'+escText(t.id)+'" style="width:100%;text-align:left;border:0;cursor:pointer"><div><b>'+escText(t.student_name||'Người dùng')+'</b><p>'+escText(t.last_message||('Thiết bị '+String(t.device_id||'').slice(0,8)))+'</p></div><span class="badge">'+(Number(t.unread_admin||0)>0?'● ':'')+escText(t.status||'open')+'</span></button>'}).join(''):'<div class="empty-chat"><span>💬</span><b>Chưa có cuộc trò chuyện</b><small>Người học gửi tin nhắn sẽ xuất hiện ở đây.</small></div>';box.querySelectorAll('[data-support-thread]').forEach(function(b){b.onclick=function(){openSupportThread(b.getAttribute('data-support-thread'))}})}catch(e){console.error('Admin support threads:',e);box.innerHTML='<div class="danger-text">Không đọc được hỗ trợ: '+escText(e&&e.message||e)+'</div>';ensureReplyComposer(!!adminSupportThread)}}
function renderMessages(rows){var box=document.getElementById('supportMessages'),head=document.getElementById('chatHeader');if(!box)return;if(head&&adminSupportThread){var tname=document.querySelector('#supportThreads [data-support-thread="'+CSS.escape(String(adminSupportThread))+'"] b');head.innerHTML='<div class="chat-person"><span class="avatar">💬</span><div><b>'+escText(tname?tname.textContent:'Hỗ trợ trực tiếp')+'</b><small>Đang trò chuyện với người học</small></div></div>'}box.innerHTML=(rows||[]).map(function(m){var mine=m.sender==='admin';var media=m.attachment_url?'<div><a href="'+escText(m.attachment_url)+'" target="_blank" rel="noopener">📎 '+escText(m.attachment_name||'Tệp đính kèm')+'</a></div>':'';return '<div class="message '+(mine?'mine':'theirs')+'" data-message-id="'+escText(m.id||'')+'"><div class="support-bubble"><b>'+(mine?'Admin':m.sender==='bot'?'Bot':'Người dùng')+'</b><div>'+escText(m.message||m.content||m.text||'')+'</div>'+media+(m.sticker?'<div style="font-size:32px">'+escText(m.sticker)+'</div>':'')+'<small>'+escText(m.created_at?new Date(m.created_at).toLocaleString('vi-VN'):'')+'</small></div></div>'}).join('')||'<div class="empty-chat"><span>💬</span><b>Chưa có tin nhắn</b></div>';requestAnimationFrame(function(){box.scrollTop=box.scrollHeight})}
async function loadThreadMessages(id,markRead){if(loadingThread)return;loadingThread=true;ensureReplyComposer(true);try{var d=await dbReady(),r=await d.from('support_messages').select('*').eq('thread_id',id).order('created_at',{ascending:true});if(r.error)throw r.error;renderMessages(r.data||[]);if(markRead)await d.from('support_threads').update({unread_admin:0}).eq('id',id)}catch(e){console.error('Admin support messages:',e);var box=document.getElementById('supportMessages');if(box)box.innerHTML='<div class="danger-text">Không tải được tin nhắn: '+escText(e&&e.message||e)+'</div>'}finally{loadingThread=false;ensureReplyComposer(true)}}
async function openSupportThread(id){if(loadingThread)return;adminSupportThread=id;ensureReplyComposer(true);await loadThreadMessages(id,true)}
async function sendAdminReply(){if(sendingReply||!adminSupportThread)return;var input=document.getElementById('replyInput'),text=input&&input.value.trim();if(!text)return;sendingReply=true;if(input)input.disabled=true;var btn=document.querySelector('#replyForm .send-btn');if(btn)btn.disabled=true;try{var d=await dbReady(),r=await d.from('support_messages').insert({thread_id:adminSupportThread,sender:'admin',message:text,bot_handled:false}).select('*').single();if(r.error)throw r.error;if(input)input.value='';ensureReplyComposer(true);await loadThreadMessages(adminSupportThread,false);await loadSupportThreads()}catch(e){console.error('Admin support send:',e);alert('Không gửi được trả lời: '+(e&&e.message||e))}finally{sendingReply=false;if(input)input.disabled=false;if(btn)btn.disabled=false;ensureReplyComposer(!!adminSupportThread)}}
window.sendAdminReply=sendAdminReply;
function bindComposer(){var form=document.getElementById('replyForm');if(!form||form.dataset.studySupportBound)return;form.dataset.studySupportBound='1';form.addEventListener('submit',function(e){e.preventDefault();e.stopImmediatePropagation();sendAdminReply()},true);var input=document.getElementById('replyInput');if(input)input.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.stopImmediatePropagation();sendAdminReply()}},true)}
function stopRealtime(){if(adminSupportRealtime&&typeof window.loadSupabase==='function'){window.loadSupabase().then(function(d){return d.removeChannel(adminSupportRealtime)}).catch(function(){});adminSupportRealtime=null}clearInterval(adminSupportPoll);adminSupportPoll=null}
async function startAdminSupportRealtime(){try{var d=await dbReady();if(adminSupportRealtime)return;adminSupportRealtime=d.channel('admin-support-stable-v5').on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages'},function(p){if(!supportActive())return;if(adminSupportThread&&String(p.new.thread_id)===String(adminSupportThread)){loadThreadMessages(adminSupportThread,false)}loadSupportThreads()}).on('postgres_changes',{event:'UPDATE',schema:'public',table:'support_threads'},function(){if(!supportActive())return;loadSupportThreads()}).subscribe(function(status){console.log('STUDY Admin support realtime:',status)});clearInterval(adminSupportPoll);adminSupportPoll=setInterval(function(){if(!supportActive())return;loadSupportThreads();if(adminSupportThread)loadThreadMessages(adminSupportThread,false)},10000)}catch(e){console.warn('Admin support realtime unavailable:',e)}}
function hookTabs(){if(typeof window.openTab!=='function'||window.openTab.__studySupportV5){if(typeof window.openTab==='function'){var native=window.openTab;var wrapped=function(id){var r=native.apply(this,arguments);if(id==='support')setTimeout(function(){bindComposer();loadSupportThreads();if(adminSupportThread)ensureReplyComposer(true);startAdminSupportRealtime()},0);return r};wrapped.__studySupportV5=true;window.openTab=wrapped}}
function boot(){bindComposer();hookTabs();if(supportActive()){loadSupportThreads();if(adminSupportThread)ensureReplyComposer(true);startAdminSupportRealtime()}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();var tries=0,timer=setInterval(function(){hookTabs();bindComposer();if(adminSupportThread)ensureReplyComposer(true);if(supportActive())startAdminSupportRealtime();if(++tries>30)clearInterval(timer)},500);
})();
