-- STUDY TH system monitor + maintenance mode
create table if not exists public.system_control (
  id boolean primary key default true check (id = true),
  maintenance boolean not null default false,
  maintenance_title text not null default 'Hệ thống đang được chăm sóc một chút 💛',
  maintenance_message text not null default 'Xin lỗi bạn nhé! STUDY TH đang được bảo trì để mọi thứ chạy ổn định hơn. Bạn quay lại sau ít phút nhé.',
  updated_at timestamptz not null default now()
);
insert into public.system_control(id) values(true) on conflict(id) do nothing;

create table if not exists public.system_incidents (
  id bigint generated by default as identity primary key,
  severity text not null default 'warning',
  area text not null,
  title text not null,
  detail text,
  status text not null default 'open',
  auto_action text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists system_incidents_status_idx on public.system_incidents(status, created_at desc);

alter table public.system_control enable row level security;
alter table public.system_incidents enable row level security;
drop policy if exists system_control_public_read on public.system_control;
create policy system_control_public_read on public.system_control for select using (true);
drop policy if exists system_control_admin_update on public.system_control;
create policy system_control_admin_update on public.system_control for update using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists system_control_admin_insert on public.system_control;
create policy system_control_admin_insert on public.system_control for insert with check (auth.role() = 'authenticated');
drop policy if exists system_incidents_admin_read on public.system_incidents;
create policy system_incidents_admin_read on public.system_incidents for select using (auth.role() = 'authenticated');
notify pgrst, 'reload schema';
