const MODELS=['gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash'];
const MAX_OUTPUT_TOKENS=12000;
const MAX_VERIFY_TOKENS=3000;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function clean(v){return String(v||'').replace(/^['"`]+|['"`]+$/g,'').trim()}
function out(res,status,payload){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');return res.end(JSON.stringify(payload))}
function getBody(req){const b=req?.body;if(b&&typeof b==='object'&&!Array.isArray(b))return b;if(typeof b==='string'){try{const x=JSON.parse(b);if(x&&typeof x==='object')return x}catch{}}return {}}
function subjectMode(subject,text){const s=(String(subject||'')+' '+String(text||'')).toLowerCase();if(/toán|math|algebra|calculus|đạo hàm|tích phân|hình học|phương trình|bất đẳng thức|xác suất/.test(s))return'math';if(/vật lý|physics|cơ học|điện|quang|dao động|sóng|nhiệt/.test(s))return'physics';if(/hóa|chemistry|phản ứng|mol|acid|base|oxi hóa|hữu cơ/.test(s))return'chemistry';return'general'}
function transient(status,msg){const m=String(msg||'').toLowerCase();return status===408||status===409||status===425||status===429||status>=500||/high demand|resource exhausted|rate limit|overloaded|temporarily unavailable/.test(m)}
function apiError(status,msg){if(status===401||status===403)return'API AI chưa được cấp quyền hoặc khóa API không hợp lệ.';if(transient(status,msg))return'AI đang bận tạm thời.';return'Bộ giải AI không phản hồi hợp lệ.'}
async function wolfram(query){const id=clean(process.env.WOLFRAM_APP_ID);if(!id||!query)return{available:false};try{const r=await fetch('https://api.wolframalpha.com/v1/result?appid='+encodeURIComponent(id)+'&i='+encodeURIComponent(query)+'&units=metric',{signal:AbortSignal.timeout(4500)});const t=await r.text();return r.ok&&t.trim()?{available:true,result:t.trim()}:{available:false}}catch{return{available:false}}}
function prompt(subject,kind,cas,message,history){return`Bạn là STUDY TH Math Solver. Dạng: ${kind}. Giải TOÀN BỘ bài từ gốc. Nếu có ảnh, đọc toàn bộ ảnh trước khi giải. Không được chỉ đưa kết luận. Trình bày: Dữ kiện → Cần tìm → Ý tưởng → biến đổi/chứng minh từng bước → điều kiện → thế ngược/kiểm tra → kết luận. Với phương trình/hàm/hệ/bất đẳng thức phải kiểm tra mất/thêm nghiệm, miền xác định và trường hợp đặc biệt. Không bịa dữ kiện mờ. Công thức dùng LaTeX. ${cas?'CAS/Wolfram tham khảo:\n'+cas:''}\nLịch sử:\n${Array.isArray(history)?history.slice(-4).map(x=>(x.role||'user')+': '+String(x.message||'')).join('\n'):''}\nĐề:\n${message}`}
function makeParts(args){const p=[{text:prompt(args.subject,args.kind,args.cas,args.message,args.history)}];const image=args.image;if(image&&/^data:image\//i.test(image)){const m=image.match(/^data:(image\/[\w.+-]+);base64,(.+)$/s);if(m)p.push({inlineData:{mimeType:m[1],data:m[2]}})}return p}
async function gemini(args){const api=clean(process.env.GEMINI_API_KEY);if(!api)throw new Error('GEMINI_API_KEY chưa được cấu hình.');const model=args.model;const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':api},body:JSON.stringify({contents:[{role:'user',parts:makeParts(args)}],generationConfig:{maxOutputTokens:args.maxOutputTokens||MAX_OUTPUT_TOKENS,thinkingConfig:{thinkingLevel:args.thinkingLevel||'medium'}}}),signal:AbortSignal.timeout(args.timeout||24000)});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw Object.assign(new Error(apiError(r.status,d?.error?.message)),{status:r.status,providerMessage:d?.error?.message});const c=d?.candidates?.[0];const answer=c?.content?.parts?.map(x=>x.text||'').join('').trim();if(answer)return{answer,model,finishReason:c?.finishReason||null};throw new Error('AI trả về rỗng.')}
async function solveWithFallback(args){let last=null;for(const model of MODELS){try{return await gemini({...args,model,thinkingLevel:args.deep?'high':'medium'})}catch(e){last=e;if(transient(e?.status,e?.providerMessage)){await sleep(200);continue}if(e?.status===401||e?.status===403)break}}throw last||new Error('Không có model Gemini nào phản hồi.')}
function parseJson(s){const t=String(s||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(t)}catch{const m=t.match(/\{[\s\S]*\}$/);if(m)try{return JSON.parse(m[0])}catch{}return null}}
async function verify({message,image,cas,candidate}){const api=clean(process.env.GEMINI_API_KEY);if(!api||!candidate)return null;const text=`Bạn là bộ kiểm định toán học của STUDY TH. Kiểm tra lời giải sau từ đầu đến cuối. Hãy: đọc lại đề; kiểm tra từng biến đổi; kiểm tra miền điều kiện; thế ngược vào đề gốc; thử giá trị mẫu/trường hợp đặc biệt; tìm phản ví dụ; kiểm tra mất/thêm nghiệm. Chỉ FAIL khi có bằng chứng lỗi. Nếu có lỗi, ghi lỗi cụ thể và hướng sửa. Trả JSON duy nhất: {"verdict":"PASS|FAIL|UNCERTAIN","issues":["..."],"tests":[{"test":"...","result":"PASS|FAIL|NOT_APPLICABLE","note":"..."}],"repair_hint":"..."}\n\nĐỀ:\n${message}\n\nCAS:\n${cas||'Không có'}\n\nLỜI GIẢI:\n${candidate.answer}`;const p=[{text}];if(image&&/^data:image\//i.test(image)){const m=image.match(/^data:(image\/[\w.+-]+);base64,(.+)$/s);if(m)p.push({inlineData:{mimeType:m[1],data:m[2]}})}try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':api},body:JSON.stringify({contents:[{role:'user',parts:p}],generationConfig:{maxOutputTokens:MAX_VERIFY_TOKENS,responseMimeType:'application/json',thinkingConfig:{thinkingLevel:'medium'}}}),signal:AbortSignal.timeout(10000)});const raw=await r.text();if(!r.ok)return null;let d={};try{d=raw?JSON.parse(raw):{}}catch{}return parseJson(d?.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join(''))}catch{return null}}
async function repair({message,subject,image,cas,candidate,audit,attempt}){return gemini({message:`Giải lại TOÀN BỘ bài toán từ đầu. Lời giải trước bị kiểm định FAIL. Sửa đúng các lỗi sau: ${JSON.stringify(audit)}. Không vá một dòng; hãy xây dựng lại lời giải, rồi tự kiểm tra thế ngược và điều kiện. Vòng sửa ${attempt}.\n\nĐề gốc:\n${message}\n\nLời giải cũ:\n${candidate.answer}`,subject,kind:subjectMode(subject,message),cas:null,history:[],image,model:'gemini-3.8-flash',thinkingLevel:'high',timeout:28000,maxOutputTokens:MAX_OUTPUT_TOKENS})}
async function openaiFallback(args){const api=clean(process.env.OPENAI_API_KEY);if(!api)return null;const model=clean(process.env.OPENAI_SOLVER_MODEL||'gpt-5');const content=[{type:'input_text',text:`Giải toàn bộ bài từ gốc, trình bày từng bước, kiểm tra điều kiện và thế ngược. ${args.cas?'Đối chiếu CAS: '+args.cas:''}\n\n${args.message}`}];if(args.image&&/^data:image\//i.test(args.image))content.push({type:'input_image',image_url:args.image,detail:'high'});const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+api},body:JSON.stringify({model,reasoning:{effort:'high'},input:[{role:'user',content}],max_output_tokens:MAX_OUTPUT_TOKENS}),signal:AbortSignal.timeout(30000)});const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d?.error?.message||('OpenAI HTTP '+r.status));return{answer:d.output_text||'',model}}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{error:'Method not allowed'});const b=getBody(req);try{const message=String(b.message||'').trim();const image=String(b.imageDataUrl||'');if(!message&&!image)return out(res,400,{error:'Thiếu đề bài hoặc ảnh.'});const subject=String(b.subject||'');const history=Array.isArray(b.history)?b.history:[];const deep=b.deep!==false;const kind=subjectMode(subject,message);const casP=(kind==='math'||kind==='physics'||kind==='chemistry')?wolfram(message):Promise.resolve({available:false});let cas=null;try{const w=await casP;cas=w.available?w.result:null}catch{}let candidate;try{candidate=await solveWithFallback({message,subject,history,image,cas,kind,deep})}catch(primary){try{const f=await openaiFallback({message,subject,image,cas});if(f?.answer)return out(res,200,{...f,tool:cas?'WolframAlpha + OpenAI fallback':'OpenAI fallback',auditVerdict:'FALLBACK'})}catch(f) {console.error('openai fallback',f?.message)}return out(res,503,{error:primary?.message||'AI đang bận hoặc chưa phản hồi. Hãy thử lại sau vài giây.'})}
let audit=null;let chosen=candidate;if(deep&&(kind==='math'||kind==='physics'||kind==='chemistry')){audit=await verify({message,image,cas,candidate});for(let i=1;i<=VERIFY_RETRIES&&audit?.verdict==='FAIL';i++){const fixed=await repair({message,subject,image,cas,candidate:chosen,audit,attempt:i}).catch(()=>null);if(!fixed)break;chosen=fixed;audit=await verify({message,image,cas,candidate:chosen})}if(audit?.verdict==='FAIL')return out(res,409,{error:'Lời giải chưa vượt qua kiểm định toán học nên chưa trả đáp án.',auditVerdict:'FAIL',auditIssues:audit.issues||[],tests:audit.tests||[]})}
const tools=[];if(cas)tools.push('WolframAlpha');if(candidate!==chosen)tools.push('Repair Engine');if(audit)tools.push('Verification Engine');return out(res,200,{answer:chosen.answer,model:chosen.model,auditModel:audit?'gemini-3.6-flash':null,auditVerdict:audit?.verdict||'UNCERTAIN',auditIssues:audit?.issues||[],tests:audit?.tests||[],tool:tools.join(' + ')||'Gemini',verified:!!cas})}catch(e){console.error('solver handler error',e);return out(res,503,{error:e?.message||'Solver tạm thời gặp lỗi.'})}}
